### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by dshombre** [Sp1rit/ArkRcon#1]
When someone use special characters, RCON recieve only QuestionMarks. Specially I am from CZE and our people are using chars as "ěščřžýáíé". I don't know if is this the same case, but it seems RCON response, if special character exists in it, is in UTF-16. http://forums.joinsquad.com/topic/26928-rcon-encoding-bug/ . Currently it looks ListPlayers() and GetChat() are affected

**Comment by Sp1rit** [comment]
Hm interesting, I didn't know there was a per-message-encoding. I'll have a look into it. Thx for the link.

**Comment by dshombre** [comment]
Actually nevermind. It's seems like ARK doesn't support Unicode chars via RCON. Packet itself have only questionmarks. So ARK's problem :/
